---
- hosts: all
  gather_facts: false
  tasks:
    - name: Authenticate to GCP with service account JSON key file
      shell: "gcloud auth activate-service-account --key-file {{ service_account_file }}"
    - name: Delete all files in GCP bucket
      shell: "gsutil rm -r gs://{{ bucket_name }}"
    - name: Delete a GCP storage bucket (bucket must be empty)
      gcp_storage_bucket:
        state: absent
        name: "{{ bucket_name }}"
        location: "{{ bucket_location }}"
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
