---
- hosts: localhost
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_REGION: "{{ aws_region }}"
  tasks:
    - name: "Delete S3 bucket on AWS : {{ bucket_name }}"
      s3_bucket:
        name: "{{ bucket_name }}"
        state: absent
