---
- name: create
  hosts: localhost
  gather_facts: yes
  tasks:
    
    - name: Install module prerequisites (Linux)
      apt:
        name:
          - git
          - python3-pip
          - python3-virtualenv
          - python3-setuptools
          - python3-docker
        update_cache: yes
        state: present
      when: ansible_os_family == "Debian"
      become: yes
      
    - name: Install docker-compose pip
      pip:
        name:
          - docker-compose

    - name: Create SockShop target directory
      tempfile:
        state: directory
        suffix: sockshop
      register: sockshop_target_dir

    - name: Clone SockShop repository
      git:
        repo: 'https://github.com/microservices-demo/microservices-demo.git'
        dest: "{{ sockshop_target_dir.path }}"

    - name: Store SockShop target dir
      set_stats:
        data:
          sockshop_dir: "{{ sockshop_target_dir.path }}"

    - name: Start SockShop
      docker_compose:
        project_src: "{{ sockshop_target_dir.path }}/deploy/docker-compose"
        project_name: SockShop
        services:
          - carts
          - carts-db
          - catalogue
          - catalogue-db
          - edge-router
          - front-end
          - orders
          - orders-db
          - payment
          - queue-master
          - rabbitmq
          - shipping
          - user
          - user-db

