---
- hosts: localhost
  environment:
    AWS_ACCESS_KEY_ID: "{{ source_aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ source_aws_secret_access_key }}"
    AWS_REGION: "{{ source_aws_region }}"
  tasks:
    - name: "Configure source node on AWS according to its type : {{ source_name }}"
      include_role:
        name: "{{ source_type }}"
