---
- hosts: localhost
  environment:
    AWS_ACCESS_KEY_ID: "{{ target_aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ target_aws_secret_access_key }}"
    AWS_REGION: "{{ target_aws_region }}"
  tasks:
    - name: "Add invocation permission of Lambda function on AWS : {{ target_name }}"
      vars:
        service: "{{ source_arn.split(':')[2] }}"
      lambda_policy:
        function_name: "{{ target_name }}"
        statement_id: "{{ service }}-{{ source_name }}"
        action: lambda:InvokeFunction
        principal: "{{ service }}.amazonaws.com"
        source_arn: "{{ source_arn }}"
