- hosts: all
  gather_facts: false
  tasks:
    - name: Set bucket notification
      s3_bucket_notification:
        state: present
        event_name: "radon_on_jpg_add"
        bucket_name: "{{ bucket_name }}"
        lambda_function_arn: "{{ function_arn }}"
        events: ["{{ events }}"]
        region: "{{ aws_region }}"
