- hosts: all
  gather_facts: no
  tasks:
    - name: Set bucket notification
      s3_bucket_notification:
        state: present
        event_name: "radon_on_jpg_add"
        bucket_name: "{{ bucket_name }}"
        lambda_function_arn: "{{ function_arn }}"
        events:  [ "{{ events }}" ]
        suffix: ".jpg"
        region: "{{ aws_region }}"