---
- hosts: localhost
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_REGION: "{{ aws_region }}"
  tasks:
    - name: "Delete Lambda function on AWS : {{ function_name }}"
      lambda:
        name: "{{ function_name }}"
        state: absent
    - name: "Delete role of Lambda function on AWS : {{ function_name }}"
      iam_role:
        name: "{{ function_role_name }}"
        state: absent
