---
- hosts: all
  become: true
  tasks:
    - name: Install Java 8 centos
      package:
        name: "java-1.8.0-openjdk.x86_64"
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - name: Update apt cache
      shell: apt-get update
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Install Java 8 ubuntu
      apt:
        name: "openjdk-8-jdk"
        state: present
        update_cache: true
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Download and unpack NiFi binary distribution
      unarchive:
        src: https://downloads.apache.org/nifi/{{ tarball_version }}/nifi-{{ tarball_version }}-bin.tar.gz
        dest: /usr/local/bin
        remote_src: true
        creates: /usr/local/bin/nifi-{{ tarball_version }}/LICENSE
    - name: Install nifi service
      shell: "/usr/local/bin/nifi-{{ tarball_version }}/bin/nifi.sh install"
      args:
        executable: /bin/bash
