- hosts: all
  gather_facts: no
  tasks: 
    - name: "Install Pypi manager"
      become: yes
      apt: 
        name: python3-pip  
        state: present 
    - name: "Install pypi_dependencies : {{ pypi_dependencies }}"
      pip:
        name: "{{ item }}"
        state: present
      loop: "{{ pypi_dependencies }}"