---
- name: configure
  hosts: all
  gather_facts: false
  tasks:
    - name: Configure Grafana dashboards for the monitored_function of user_email
      uri:
        url: "{{ grafana_api_ip }}"
        method: POST
        body_format: json
        body:
          "email": "{{ user_email }}"
          "jobid": "{{ monitored_function }}"
          "type": "custom"
    - name: Authenticate to GCP with service account JSON key file
      shell: "gcloud auth activate-service-account --key-file {{ service_account_file }}"
    - name: Inject the PUSH_GATEWAY_HOST ebv variable to the function to create the GCP-PushGateway relation
      shell: "gcloud functions deploy {{ monitored_function }} --set-env-vars PUSH_GATEWAY_HOST={{ pushgateway_ip }}:9091"
