---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Add "{{ record }}"
      community.aws.route53:
        alias: true
        alias_hosted_zone_id: "{{ alias_zone }}"
        zone: "{{ zone }}"
        state: present
        record: "{{ record }}"
        type: A
        value: "{{ endpoint_url }}"
