---
- hosts: localhost
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_REGION: "{{ aws_region }}"
  tasks:
    - name: "Create S3 bucket on AWS : {{ bucket_name }}"
      s3_bucket:
        name: "{{ bucket_name }}"
        state: present
    - name: "Return ARN of S3 bucket on AWS : {{ bucket_name }}"
      set_stats:
        data:
          id: "{{ 'arn:aws:s3:::' + bucket_name }}"
