---
- hosts: all
  gather_facts: no
  tasks:
    - name: Remove function
      gcp_cloudfunctions_cloud_function:
        name: "{{ function_name }}"
        location: "{{ function_location }}"
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
        state: absent
