---
- name: configure AWS
  hosts: localhost
  gather_facts: false
  tasks:
    - name: install awscli
      pip:
        name: awscli
        state: present
        extra_args: --user

    - name: install boto
      pip:
        name: boto
        state: present
        extra_args: --user

    - name: install boto3
      pip:
        name: boto3
        state: present
        extra_args: --user   
     
    - name: install botocore
      pip:
        name: botocore
        state: present
        extra_args: --user

    - name: Create global AWS role
      iam_role:
        name: global-serverless-role
        state: present
        assume_role_policy_document: "{{ lookup('file','policy.json') }}"
        managed_policy:
          -  arn:aws:iam::aws:policy/AWSLambdaFullAccess
      register: iam_role_response

    - name: Set attributes
      set_stats:
        data: 
          role_arn: "{{iam_role_response.arn}}"
