- hosts: all
  gather_facts: false
  tasks:
    - name: "Create Lambda AWS role : {{ role_name }}"
      iam_role:
        name: "{{ role_name }}"
        state: present
        description: "{{ role_description }}"
        assume_role_policy_document: "{{ lookup('file','/tmp/policy.json') }}"
        managed_policy:
          - arn:aws:iam::aws:policy/AWSLambdaFullAccess
      register: iam_role_response
    - name: Set attributes
      set_stats:
        data:
          role_arn: "{{ iam_role_response.arn }}"
