---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: "Remove S3 bucket {{ bucket_name }}"
      s3_bucket:
        name: "{{ bucket_name }}"
        region: "{{ aws_region }}"
        state: absent
        force: true
