---
- hosts: all
  tasks:
    - name: Stop the pipeline
      uri:
        url: "http://localhost:8080/nifi-api/flow/process-groups/{{pipeline_id}}"
        method: PUT
        body:
          "id": "{{pipeline_id}}"
          "state": "STOPPED" 
        status: 201
        body_format: json

