- name: create
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Install Python pip module prerequisites (Linux)
      apt:
        name:
          - python3-pip
          - python3-virtualenv
          - python3-setuptools
          - python3-docker
        update_cache: yes
        state: present
      when: ansible_os_family == "Debian"
      become: yes

    - name: Run JMeterAgent Docker image
      docker_container:
        name: JMeterAgent
        image: radonconsortium/radon-ctt-agent:jmeter
        ports: 
          - "5000:5000"

