- name: create
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Install Python pip module prerequisites (Linux)
      package:
        name:
          - python3-pip
          - python3-virtualenv
          - python3-setuptools
          - python3-docker
        state: present
      when: ansible_os_family == "Debian"
      become: yes

    - name: Install Python pip module prerequisites (Arch Linux)
      pacman:
        name:
          - python-pip
          - python-virtualenv
          - python-setuptools
          - python-docker
        state: present
      when: ansible_os_family == "Archlinux"
      become: yes

    - name: Run JMeterAgent Docker image
      docker_container:
        name: JMeterAgent
        image: radonconsortium/radon-ctt-agent:jmeter
        ports: 
          - "5000:5000"

