---
- hosts: all
  tasks:
    - name: Get process group info
      uri:
        url: "http://localhost:8080/nifi-api/process-groups/{{pipeline_id}}"
        method:  GET
      register: group_info

    - name: Delete the pipeline
      uri:
        url: "http://localhost:8080/nifi-api/process-groups/{{pipeline_id}}?version={{group_info.json.revision.version}}&clientId={{group_info.json.revision.clientId }}"
        method: DELETE
        body_format: form-urlencoded


