---
  - hosts: localhost
    vars:
       ansible_python_interpreter: /usr/bin/python3
    tasks:
      - name: Edit Pipeline definition
        shell: aws datapipeline put-pipeline-definition --pipeline-id {{ pipeline_id }} --parameter-values myDDBRegion={{ dynamodb_region }} myLogBucket=s3://{{ log_bucket }}/{{ log_directory }} mySchedule="{{ edit_schedule }}" myDDBTableName="{{ dynamodb_table }}" myDDBReadThroughputRatio={{ throughput_ratio }} myInputS3Loc=s3://{{ source_s3 }}//{{ source_s3_directory }} --pipeline-definition file://S3ToDynamodb.json
        when: sns_arn_topic=="None"
      - name: edit template file
        script: edit_template.py S3ToDynamodb.json
        when: sns_arn_topic!="None"
      - name: Edit Pipeline definition
        shell: aws datapipeline put-pipeline-definition --pipeline-id {{ pipeline_id }} --parameter-values myDDBRegion={{ dynamodb_region }} myLogBucket=s3://{{ log_bucket }}/{{ log_directory }} mySchedule="{{ edit_schedule }}" myDDBTableName="{{ dynamodb_table }}" myDDBReadThroughputRatio={{ throughput_ratio }} myInputS3Loc=s3://{{ source_s3 }}//{{ source_s3_directory }} myArnTopic="{{ sns_arn_topic }}" --pipeline-definition file://S3ToDynamodb.json
        when: sns_arn_topic!="None"
