---
- hosts: all
  gather_facts: false
  tasks:
    - name: Install required packages
      pip:
        name:
          - requests>=2.18.4
          - google-auth>=1.3.0
          - google-cloud==0.34.0
        state: latest
