---
- hosts: all
  gather_facts: no
  tasks:
    - name: Install required packages
      pip:
        name:
          - requests>=2.18.4
          - google-auth>=1.3.0
          - google-cloud==0.34.0
        state: latest

    - name: Create a GCP storage bucket
      gcp_storage_bucket:
        name: "{{ bucket_name }}"
        location: "{{ bucket_location }}"
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
