---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create S3 bucket "{{ bucket_name }}"
      aws_s3:
        bucket: "{{ bucket_name }}"
        mode: create
        region: "{{ aws_region }}"
    - name: Set attributes
      set_stats:
        data:
          bucket_name: "{{ bucket_name }}"
          region: "{{ aws_region }}"
          bucket_url_vhost: "https://s3.{{ aws_region }}.amazonaws.com/{{ bucket_name }}"
          bucket_url_path: "https://{{ bucket_name }}.s3.{{ aws_region }}.amazonaws.com"
