---
- hosts: localhost
  tasks:
    - name: "Delete role of Lambda function on AWS : {{ function_name }}"
      iam_role:
        name: "{{ aws_role }}"
        state: absent

    - name: "Remove function alias name"
      lambda_alias:
        function_name: "{{ function_name }}"
        name: "{{ func_alias }}"
        region: "{{ aws_region }}"
        state: absent
      ignore_errors: yes

    - name: "Lambda {{ function_name }} undeploy"
      lambda:
        name: "{{ function_name }}"
        region: "{{ aws_region }}"
        role: "{{ aws_role }}"
        handler: image_resize.lambda_handler
        state: absent
