---
  - hosts: localhost
    vars:
       ansible_python_interpreter: /usr/bin/python3
    tasks:
      - name: Edit Pipeline definition
        shell: aws datapipeline put-pipeline-definition --pipeline-id {{ pipeline_id }} --parameter-values myAWSCLICmd="{{ aws_cli_command }}" myLogBucket=s3://{{ log_bucket }}/{{ log_directory }} mySchedule="{{ edit_schedule }}" --pipeline-definition file://ShellCommandActivity.json
        when: sns_arn_topic=="None"
      - name: edit template file
        script: edit_template.py ShellCommandActivity.json
        when: sns_arn_topic!="None"
      - name: Edit Pipeline definition
        shell: aws datapipeline put-pipeline-definition --pipeline-id {{ pipeline_id }} --parameter-values myAWSCLICmd="{{ aws_cli_command }}" myLogBucket=s3://{{ log_bucket }}/{{ log_directory }} mySchedule="{{ edit_schedule }}" myArnTopic="{{ sns_arn_topic }}" --pipeline-definition file://ShellCommandActivity.json
        when: sns_arn_topic!="None"
